---
title: "CDS-490 Project"
author: "Jon Kashmeeri"
date: "2/16/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Data

```{r loadData}

library(readr)
SP_dataset <- read_csv("^GSPC.csv")

library(readr)
DJ_dataset <- read_csv("^DJI.csv")

library(readr)
Nas_dataset <- read_csv("^GSPC.csv")

```


## Load Packages

```{r loadPackages}

library('dplyr')
library('tidyverse')

```


##Wrangle Data

```{r}

fixed_DJ_dataset <- DJ_dataset %>%
  separate (Date, c("month","day","year"))

final_DJ_dataset <- fixed_DJ_dataset %>%
  group_by(month) %>%
  summarise(MonthlyOpenAverage = mean(Open), MonthlyAdjCloseAverage = mean(`Adj Close`), MonthlyMaxHigh = max(High), MonthlyMinLow = min(Low), MonthlyVolumeAverage = mean(Open), .groups = 'rowwise')

```

```{r}

fixed_SP_dataset <- SP_dataset %>%
  separate (Date, c("month","day","year"))

final_SP_dataset <- fixed_SP_dataset %>%
  group_by(month) %>%
  summarise(MonthlyOpenAverage = mean(Open), MonthlyAdjCloseAverage = mean(`Adj Close`), MonthlyMaxHigh = max(High), MonthlyMinLow = min(Low), MonthlyVolumeAverage = mean(Open), .groups = 'rowwise')

```

```{r}

fixed_Nas_dataset <- Nas_dataset %>%
  separate (Date, c("month","day","year"))

final_Nas_dataset <- fixed_Nas_dataset %>%
  group_by(month) %>%
  summarise(MonthlyOpenAverage = mean(Open), MonthlyAdjCloseAverage = mean(`Adj Close`), MonthlyMaxHigh = max(High), MonthlyMinLow = min(Low), MonthlyVolumeAverage = mean(Open), .groups = 'rowwise')

```


## Test Plots

```{r}

ggplot(final_DJ_dataset, aes(MonthlyOpenAverage,MonthlyAdjCloseAverage))+
  geom_point()

```

```{r}

ggplot(final_SP_dataset, aes(MonthlyOpenAverage,MonthlyAdjCloseAverage))+
  geom_point()

```

```{r}

ggplot(final_Nas_dataset, aes(MonthlyOpenAverage,MonthlyAdjCloseAverage))+
  geom_point()

```
















